version: '3.7'

services:

  api:
    image: codait/max-image-segmenter
    stdin_open: true
    tty: true
    ports:
      - 5110:5000
      - 8070:3000

  web:
    image: codait/max-image-segmenter-web-app
    network_mode: service:api
